// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGBUbn_2AU0q3jWlAqwwTpFT19-Clwhk4',
    appId: '1:669781500597:web:6c8cbc0ebd0cd7153694fc',
    messagingSenderId: '669781500597',
    projectId: 'todo-project-7a37e',
    authDomain: 'todo-project-7a37e.firebaseapp.com',
    storageBucket: 'todo-project-7a37e.appspot.com',
    measurementId: 'G-S7FJF1N6MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKpgC_ft1S5W7KUlU_U_bXA96kBUnM9eQ',
    appId: '1:669781500597:android:f210b921918995733694fc',
    messagingSenderId: '669781500597',
    projectId: 'todo-project-7a37e',
    storageBucket: 'todo-project-7a37e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ04t8B1C-KBkq4kRS58CfjbVHCwKJfxk',
    appId: '1:669781500597:ios:517accaa26f605a33694fc',
    messagingSenderId: '669781500597',
    projectId: 'todo-project-7a37e',
    storageBucket: 'todo-project-7a37e.appspot.com',
    iosClientId: '669781500597-1m6mcdf6tis92lsdc83av2m7vmoqba8q.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
